hosts:
  - "xmpp.elenty.com"

loglevel: 5
log_rotate_size: 10485760
log_rotate_count: 100

## If you already have certificates, list them here
# certfiles:
#  - /etc/letsencrypt/live/domain.tld/fullchain.pem
#  - /etc/letsencrypt/live/domain.tld/privkey.pem

registration_timeout: infinity

sql_type: mysql
sql_server: "localhost"
sql_port: 3306
sql_database: "ejabberd"
sql_username: "ejabberd"
sql_password: "password"
sql_pool_size: 5

listen:
  - port: 13340
    module: ejabberd_http
    request_handlers:
      "/api/send_message": mod_elenty_send_message_api
  - port: 13338
    module: ejabberd_c2s
    max_stanza_size: 10240
    shaper: c2s_shaper
    access: c2s
    #stream_management: true
    #resend_on_timeout: true
    #resume_timeout: 15
  - port: 5269
    module: ejabberd_s2s_in
    tls_compression: false
  - port: 13339
    module: ejabberd_http
    request_handlers:
      "/api/registration": mod_elenty_registration_api

# s2s_use_starttls: optional

acl:
  admin:
    user:
      - "admin": "xmpp.elenty.com"
  local:
    user_regexp: ""
  loopback:
    ip:
      - "127.0.0.0/8"

access_rules:
  local:
    allow: local
  c2s:
    deny: blocked
    allow: all
  announce:
    allow: admin
  configure:
    allow: admin
  muc_create:
    allow: local
  pubsub_createnode:
    allow: local
  trusted_network:
    allow: loopback

# commands_admin_access: xmlrpc_access

# api_permissions:
#   "console commands":
#     from:
#       - ejabberd_ctl
#     who: all
#     what: "*"
#   "admin access":
#     who:
#       access:
#         allow:
#           - acl: loopback
#           - acl: admin
#       oauth:
#         scope: "ejabberd:admin"
#         access:
#           allow:
#             - acl: loopback
#             - acl: admin
#     what:
#       - "*"
#       - "!stop"
#       - "!start"
#   "public commands":
#     who:
#       ip: 127.0.0.1/8
#     what:
#       - status
#       - connected_users_number
shaper:
  normal:
    rate: 3000
    burst_size: 20000
  fast: 50000

shaper_rules:
  max_user_sessions: 1
  max_user_offline_messages:
    5000: admin
    100: all
  c2s_shaper:
    none: admin
    normal: all
  s2s_shaper: fast

modules:
  # mod_adhoc: {}
  # mod_announce:
  #   access: announce
  # mod_avatar: {}
  # mod_blocking: {}
  # mod_bosh: {}
  # mod_caps: {}
  # mod_carboncopy: {}
  # mod_client_state: {}
  # mod_configure: {}
  mod_disco: {}
  # mod_fail2ban: {}
  # mod_http_api: {}
  # mod_http_upload:
  #   put_url: https://@HOST@:5443/upload
  #   custom_headers:
  #     "Access-Control-Allow-Origin": "https://@HOST@"
  #     "Access-Control-Allow-Methods": "GET,HEAD,PUT,OPTIONS"
  #     "Access-Control-Allow-Headers": "Content-Type"
  # mod_last:
  #     db_type: mnesia
  mod_elenty_last:
      db_type: mnesia
  # mod_mam:
    ## Mnesia is limited to 2GB, better to use an SQL backend
    ## For small servers SQLite is a good fit and is very easy
    ## to configure. Uncomment this when you have SQL configured:
    # ## db_type: sql
    # assume_mam_usage: true
    # default: always
  # mod_mqtt: {}
  # mod_muc:
  #   access:
  #     - allow
  #   access_admin:
  #     - allow: admin
  #   access_create: muc_create
  #   access_persistent: muc_create
  #   access_mam:
  #     - allow
  #   default_room_options:
  #     mam: true
  # mod_muc_admin: {}
  mod_ping:
      send_pings: false
      ping_interval: 58
  # mod_privacy: {}
  # mod_private: {}
  # mod_proxy65:
  #   access: local
  #   max_connections: 5
  # mod_pubsub:
  #   access_createnode: pubsub_createnode
  #   plugins:
  #     - flat
  #     - pep
  #   force_node_config:
  #     ## Avoid buggy clients to make their bookmarks public
  #     storage:bookmarks:
  #       access_model: whitelist
  # mod_push: {}
  # mod_push_keepalive: {}
  # mod_register:
  #   ## Only accept registration requests from the "trusted"
  #   ## network (see access_rules section above).
  #   ## Think twice before enabling registration from any
  #   ## address. See the Jabber SPAM Manifesto for details:
  #   ## https://github.com/ge0rg/jabber-spam-fighting-manifesto
  #   ip_access: trusted_network
  # mod_s2s_dialback: {}
  # mod_shared_roster: {}
  # mod_stun_disco: {}
  # mod_vcard: {}
  # mod_vcard_xupdate: {}

  ### Local Variables:
  ### mode: yaml
  ### End:
  ### vim: set filetype=yaml tabstop=8
  # mod_elenty_offlineretrieval: {}
  mod_offline:
    access_max_user_messages: max_user_offline_messages
    use_cache: false
    db_type: sql
  mod_roster: {}
  # mod_elenty_ping: {}
    # send_pings: true
    # ping_interval: 58
    # timeout_action: kill
  mod_stats: {}
  mod_time: {}
  mod_admin_extra: {}
  mod_version: {}
  # mod_elenty_metrics: {}
  # mod_elenty_metrics_hooks: {}
  mod_elenty_servertimestamp: {}
  mod_elenty_broadcastmsg: {}
  mod_elenty_registration_api: {}
  mod_stream_mgmt:
    resend_on_timeout: true
    resume_timeout: 15
  mod_gcm: {}
  #   gcm_api_key: "AAAAyfo-2BU:APA91bH-62f112PSR8demaqk9oUD-P5K4NRXkddhku3QzunDgunQQ9GX4_IeSTume1PKOBTHVV4XrlgWnovrbi2Gz7HmhIU_2A1ZxohpC9AokAHK34yeI3lvFEsZKpwlF3i_dy1pwscX"
  mod_elenty_delete_messages: {}
  mod_fcm: {}
    # url_send: "http://172.17.0.1:3456"
